//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes.Conexoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIDADOES
    {
        public long CIDADAO { get; set; }
        public string NOME { get; set; }
        public string EMAIL { get; set; }
        public string END { get; set; }
        public int CEP { get; set; }
        public long TEL { get; set; }
        public long CEL { get; set; }
        public System.DateTime D_NASCIMENTO { get; set; }
        public long CPF { get; set; }
        public byte[] CPF_DOC { get; set; }
        public string RG { get; set; }
        public byte[] RG_DOC { get; set; }
        public string CNH { get; set; }
        public byte[] CNH_DOC { get; set; }
        public byte[] FOTO { get; set; }
        public string NOME_SOCIAL { get; set; }
        public System.DateTime DATA_CADASTRO { get; set; }
        public string N_PAI { get; set; }
        public string N_MAE { get; set; }
        public short GENERO { get; set; }
        public string NATURALIDADE { get; set; }
    }
}
