//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes.Conexoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ERROS
    {
        public long LOG_ERRO { get; set; }
        public System.DateTime DATA { get; set; }
        public string ERRO { get; set; }
        public string DETALHE_COMPLETO { get; set; }
        public string DETALHE_RESUMENDO { get; set; }
        public long USUARIO { get; set; }
        public string MAC_ADRES { get; set; }
        public byte[] PRINT_TELA { get; set; }
    }
}
