//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes.Conexoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGS
    {
        public long ID_LOG { get; set; }
        public System.DateTime DATA { get; set; }
        public string CHAVE { get; set; }
        public string DESTALHES { get; set; }
        public long USUARIO { get; set; }
        public string MAC_ADRESS { get; set; }
    }
}
