//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes.Conexoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public long USUARIO { get; set; }
        public string NOME { get; set; }
        public string EMAIL { get; set; }
        public string ENDERECO { get; set; }
        public Nullable<int> CEP { get; set; }
        public Nullable<long> TEL { get; set; }
        public Nullable<System.DateTime> DN_NASCIMENTO { get; set; }
        public long CPF { get; set; }
        public string RG { get; set; }
        public short ATIVO { get; set; }
    }
}
